-- AlterEnum
ALTER TYPE "ChallengeStatus" ADD VALUE IF NOT EXISTS 'PENDING_REVIEW';
ALTER TYPE "ChallengeStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CHALLENGE_REVIEW_REQUEST';
